ALTER TABLE order_items
    ADD COLUMN price_at_order DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN discount_at_order INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN final_price_at_order DOUBLE PRECISION NOT NULL DEFAULT 0;
