// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/cache_service/cache_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	cacheservice "kingcom_api/internal/services/cache_service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCacheService is a mock of CacheService interface.
type MockCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockCacheServiceMockRecorder
}

// MockCacheServiceMockRecorder is the mock recorder for MockCacheService.
type MockCacheServiceMockRecorder struct {
	mock *MockCacheService
}

// NewMockCacheService creates a new mock instance.
func NewMockCacheService(ctrl *gomock.Controller) *MockCacheService {
	mock := &MockCacheService{ctrl: ctrl}
	mock.recorder = &MockCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheService) EXPECT() *MockCacheServiceMockRecorder {
	return m.recorder
}

// DeleteAccessToken mocks base method.
func (m *MockCacheService) DeleteAccessToken(ctx context.Context, jti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessToken", ctx, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessToken indicates an expected call of DeleteAccessToken.
func (mr *MockCacheServiceMockRecorder) DeleteAccessToken(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessToken", reflect.TypeOf((*MockCacheService)(nil).DeleteAccessToken), ctx, jti)
}

// DeletePasswordResetToken mocks base method.
func (m *MockCacheService) DeletePasswordResetToken(ctx context.Context, hashedToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePasswordResetToken", ctx, hashedToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePasswordResetToken indicates an expected call of DeletePasswordResetToken.
func (mr *MockCacheServiceMockRecorder) DeletePasswordResetToken(ctx, hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePasswordResetToken", reflect.TypeOf((*MockCacheService)(nil).DeletePasswordResetToken), ctx, hashedToken)
}

// DeleteRefreshToken mocks base method.
func (m *MockCacheService) DeleteRefreshToken(ctx context.Context, hashedToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, hashedToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockCacheServiceMockRecorder) DeleteRefreshToken(ctx, hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockCacheService)(nil).DeleteRefreshToken), ctx, hashedToken)
}

// DeleteVerificationToken mocks base method.
func (m *MockCacheService) DeleteVerificationToken(ctx context.Context, hashedToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVerificationToken", ctx, hashedToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVerificationToken indicates an expected call of DeleteVerificationToken.
func (mr *MockCacheServiceMockRecorder) DeleteVerificationToken(ctx, hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVerificationToken", reflect.TypeOf((*MockCacheService)(nil).DeleteVerificationToken), ctx, hashedToken)
}

// FindAccessToken mocks base method.
func (m *MockCacheService) FindAccessToken(ctx context.Context, jti string) (*cacheservice.AccessTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccessToken", ctx, jti)
	ret0, _ := ret[0].(*cacheservice.AccessTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccessToken indicates an expected call of FindAccessToken.
func (mr *MockCacheServiceMockRecorder) FindAccessToken(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccessToken", reflect.TypeOf((*MockCacheService)(nil).FindAccessToken), ctx, jti)
}

// FindPasswordResetToken mocks base method.
func (m *MockCacheService) FindPasswordResetToken(ctx context.Context, hashedToken string) (*cacheservice.PasswordResetTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPasswordResetToken", ctx, hashedToken)
	ret0, _ := ret[0].(*cacheservice.PasswordResetTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPasswordResetToken indicates an expected call of FindPasswordResetToken.
func (mr *MockCacheServiceMockRecorder) FindPasswordResetToken(ctx, hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPasswordResetToken", reflect.TypeOf((*MockCacheService)(nil).FindPasswordResetToken), ctx, hashedToken)
}

// FindRefreshToken mocks base method.
func (m *MockCacheService) FindRefreshToken(ctx context.Context, hashedToken string) (*cacheservice.RefreshTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshToken", ctx, hashedToken)
	ret0, _ := ret[0].(*cacheservice.RefreshTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRefreshToken indicates an expected call of FindRefreshToken.
func (mr *MockCacheServiceMockRecorder) FindRefreshToken(ctx, hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshToken", reflect.TypeOf((*MockCacheService)(nil).FindRefreshToken), ctx, hashedToken)
}

// FindShippingProvinces mocks base method.
func (m *MockCacheService) FindShippingProvinces(ctx context.Context) (*cacheservice.SaveProvincesData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShippingProvinces", ctx)
	ret0, _ := ret[0].(*cacheservice.SaveProvincesData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShippingProvinces indicates an expected call of FindShippingProvinces.
func (mr *MockCacheServiceMockRecorder) FindShippingProvinces(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShippingProvinces", reflect.TypeOf((*MockCacheService)(nil).FindShippingProvinces), ctx)
}

// FindVerificationToken mocks base method.
func (m *MockCacheService) FindVerificationToken(ctx context.Context, hashedToken string) (*cacheservice.VerificationTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVerificationToken", ctx, hashedToken)
	ret0, _ := ret[0].(*cacheservice.VerificationTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVerificationToken indicates an expected call of FindVerificationToken.
func (mr *MockCacheServiceMockRecorder) FindVerificationToken(ctx, hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVerificationToken", reflect.TypeOf((*MockCacheService)(nil).FindVerificationToken), ctx, hashedToken)
}

// SaveAccessToken mocks base method.
func (m *MockCacheService) SaveAccessToken(ctx context.Context, jti string, payload cacheservice.AccessTokenPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAccessToken", ctx, jti, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAccessToken indicates an expected call of SaveAccessToken.
func (mr *MockCacheServiceMockRecorder) SaveAccessToken(ctx, jti, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAccessToken", reflect.TypeOf((*MockCacheService)(nil).SaveAccessToken), ctx, jti, payload)
}

// SavePasswordResetToken mocks base method.
func (m *MockCacheService) SavePasswordResetToken(ctx context.Context, hashedToken string, payload cacheservice.PasswordResetTokenPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePasswordResetToken", ctx, hashedToken, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePasswordResetToken indicates an expected call of SavePasswordResetToken.
func (mr *MockCacheServiceMockRecorder) SavePasswordResetToken(ctx, hashedToken, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePasswordResetToken", reflect.TypeOf((*MockCacheService)(nil).SavePasswordResetToken), ctx, hashedToken, payload)
}

// SaveRefreshToken mocks base method.
func (m *MockCacheService) SaveRefreshToken(ctx context.Context, hashedToken string, payload cacheservice.RefreshTokenPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, hashedToken, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockCacheServiceMockRecorder) SaveRefreshToken(ctx, hashedToken, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockCacheService)(nil).SaveRefreshToken), ctx, hashedToken, payload)
}

// SaveShippingProvinces mocks base method.
func (m *MockCacheService) SaveShippingProvinces(ctx context.Context, params cacheservice.SaveProvincesData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShippingProvinces", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveShippingProvinces indicates an expected call of SaveShippingProvinces.
func (mr *MockCacheServiceMockRecorder) SaveShippingProvinces(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShippingProvinces", reflect.TypeOf((*MockCacheService)(nil).SaveShippingProvinces), ctx, params)
}

// SaveVerificationToken mocks base method.
func (m *MockCacheService) SaveVerificationToken(ctx context.Context, hashedToken string, payload cacheservice.VerificationTokenPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVerificationToken", ctx, hashedToken, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveVerificationToken indicates an expected call of SaveVerificationToken.
func (mr *MockCacheServiceMockRecorder) SaveVerificationToken(ctx, hashedToken, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVerificationToken", reflect.TypeOf((*MockCacheService)(nil).SaveVerificationToken), ctx, hashedToken, payload)
}

// SetAccessTokenKey mocks base method.
func (m *MockCacheService) SetAccessTokenKey(jti string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAccessTokenKey", jti)
	ret0, _ := ret[0].(string)
	return ret0
}

// SetAccessTokenKey indicates an expected call of SetAccessTokenKey.
func (mr *MockCacheServiceMockRecorder) SetAccessTokenKey(jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccessTokenKey", reflect.TypeOf((*MockCacheService)(nil).SetAccessTokenKey), jti)
}

// SetPasswordResetTokenKey mocks base method.
func (m *MockCacheService) SetPasswordResetTokenKey(hashedToken string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPasswordResetTokenKey", hashedToken)
	ret0, _ := ret[0].(string)
	return ret0
}

// SetPasswordResetTokenKey indicates an expected call of SetPasswordResetTokenKey.
func (mr *MockCacheServiceMockRecorder) SetPasswordResetTokenKey(hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPasswordResetTokenKey", reflect.TypeOf((*MockCacheService)(nil).SetPasswordResetTokenKey), hashedToken)
}

// SetRefreshTokenKey mocks base method.
func (m *MockCacheService) SetRefreshTokenKey(hashedToken string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefreshTokenKey", hashedToken)
	ret0, _ := ret[0].(string)
	return ret0
}

// SetRefreshTokenKey indicates an expected call of SetRefreshTokenKey.
func (mr *MockCacheServiceMockRecorder) SetRefreshTokenKey(hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefreshTokenKey", reflect.TypeOf((*MockCacheService)(nil).SetRefreshTokenKey), hashedToken)
}

// SetShippingProvincesKey mocks base method.
func (m *MockCacheService) SetShippingProvincesKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShippingProvincesKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// SetShippingProvincesKey indicates an expected call of SetShippingProvincesKey.
func (mr *MockCacheServiceMockRecorder) SetShippingProvincesKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShippingProvincesKey", reflect.TypeOf((*MockCacheService)(nil).SetShippingProvincesKey))
}

// SetVerificationTokenKey mocks base method.
func (m *MockCacheService) SetVerificationTokenKey(hashedToken string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVerificationTokenKey", hashedToken)
	ret0, _ := ret[0].(string)
	return ret0
}

// SetVerificationTokenKey indicates an expected call of SetVerificationTokenKey.
func (mr *MockCacheServiceMockRecorder) SetVerificationTokenKey(hashedToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerificationTokenKey", reflect.TypeOf((*MockCacheService)(nil).SetVerificationTokenKey), hashedToken)
}
